name = "intellij"
title = "MongoDB for IntelliJ Plugin"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = ["/connect"]

[constants]
intellij-full = "MongoDB for IntelliJ Plugin"
intellij-short = "IntelliJ Plugin"

[[banners]]
targets = ["*"]
variant = "info"
value = "The MongoDB for IntelliJ Plugin is currently in Private Preview."
